### PR TITLE
Hotfix `-e` substitution

### PR DESCRIPTION
**Pull request by kaste**

### CODE REVIEW

**Comment by kaste** [comment]
@braver 🚑

**Comment by braver** [comment]
I can't really test this, so if you're sure this work (or is less broken than our previous thing) then let's ⛵️

**Comment by kaste** [comment]
Don't have merge/release rights in this repo.

**Comment by braver** [comment]
Well, that's certainly not correct. Now you do.

**Comment by kaste** [comment]
👍

**Pull request merged**
