### PR TITLE
Lint also _test files.

### LINKED ISSUE #9: Linter skips _test.go files
I can see errors in regular go files but I cannot see errors in my _test.go files in the same package. I tried to use argument "-t" but I get an error:  

```
Traceback (most recent call last):
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1410, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1749, in find_errors
    yield self.split_match(self.regex.match(line.rstrip()))
  File "linter in /Users/nicholasphillips/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-gotype.sublime-package", line 43, in split_match
AttributeError: 'NoneType' object has no attribute 'group'
```

### PR DESCRIPTION
**Pull request by rasky**
Fixes #9

### CODE REVIEW

**Comment by kaste** [comment]
Hi!

Currently (and with this patch) we would call `gotype -t -e <some_path>` but then we have to throw away all problems coming from a different file than the view's file. (You see that filter in `split_match`). Wouldn't it be better to just `stdin | gotype -e` so it actually only ever sees the current buffer?

**Comment by kaste** [comment]
Also: Is there are good default for 'GOPATH'? For example we could set it to `${folder}` which usually resolves to the Sublime project folder.

**Comment by kaste** [comment]
Ah, okay, the confusing thing is that this linter is configured like a stdin linter. (We actually send the buffer to gotype.) Shouldn't we configure this thing as 'saved-files' only linter? 

Also this from https://godoc.org/golang.org/x/tools/cmd/gotype is confusing. 

```
Without a list of paths, gotype reads from standard input, which must provide a single Go source file defining a complete package.
```

Is that something we never need to support?

**Comment by kaste** [comment]
Same docs list also this example

```
gotype a.go b.go c.go
```

So we could also use just that `gotype ${file}`

**Comment by rasky** [comment]
> Ah, okay, the confusing thing is that this linter is configured like a stdin linter. (We actually send the buffer to gotype.) Shouldn't we configure this thing as 'saved-files' only linter?

Ah yes, absolutely. I wasn't aware of this distinction but go ahead.

> Also this from https://godoc.org/golang.org/x/tools/cmd/gotype is confusing.
>> Without a list of paths, gotype reads from standard input, which must provide a single Go source file defining a complete package.

That is again the same of `go build`. Normally, `go build` means `go build .`. 

If you say `go build foo.go` what it really means is "build `foo.go` like it was the only file in this directory". You can also say `go build foo.go bar.go` which means "build `foo.go` and `bar.go` together like they were the only files here".  The same applies to `gotype`.

This is rarely useful; I personally use it when I have throwaway code so I might have a "dummy" directory in which I have many unrelated files, and in that case I build only single files. In that case, this linter does complain with spurious errors (eg: duplicate `main()` function) but I just live with it as it's by far a rare case, and also I mostly don't need advanced linters when writing throwaway code.

> Is that something we never need to support?

If we want to support the above scenario ("many unrelated files in the same directory"), it must be something that is configured at the directory level or file level, so that the liner knows that, if the file is in that specific directory, it must run `gotype filename.go` (or through stdin) as an exception to the rule. I wouldn't know how to design this in a way that's simple to use to Sublime users though, and if it's too complex to configure, I would personally just ignore it.

**Comment by rasky** [comment]
> Same docs list also this example
> gotype a.go b.go c.go
>So we could also use just that gotype ${file}

No you cannot. As I said above, that would mean "ignore all the other files", which means that gotype will report many errors about unknown symbols (eg: classes) that are used in a/b/c but defined in d/e/f.

**Comment by kaste** [comment]
Hm, then we maybe just go with `gotype -t -e .` and use `$file_path` or `$folder` for the default working dir? I mean if you have deep structure `a/b/c.go` and `a/d/f.go`. Does it even make sense to call gotype on `a/b/*` when editing `c.go`? Bc you can likely have sibling imports, like `c.go` depends on something in `a/d/f.go`? So isn't it better to call `gotype -t -e a/` all the time?

((Also: We have this https://github.com/SublimeLinter/SublimeLinter-golint/blob/9c743915ebee3fc0b1953975a3a6f29ca2bb1a31/linter.py#L36-L60 for `golint` where some code from 2014 augments the GOPATH. Should we just remove this code?))

**Comment by rasky** [comment]
> Hm, then we maybe just go with gotype -t -e . and use $file_path or $folder for the default working dir? 

Yes, that would be correct.

> I mean if you have deep structure a/b/c.go and a/d/f.go. Does it even make sense to call gotype on a/b/* when editing c.go? Bc you can likely have sibling imports, like c.go depends on something in a/d/f.go? 

That's by default. Everything in c.go depends automatically on everything in f.go, if they are in the same directory. The directory is the minimal translation unit. This is why you need to build by directory and lint by directory.

> So isn't it better to call gotype -t -e a/ all the time?

That's too much, it can cause slower feedback to the user for no good reason. If you're touching a file in the directory, it's that directory the correct linting point.

> ((Also: We have this https://github.com/SublimeLinter/SublimeLinter-golint/blob/9c743915ebee3fc0b1953975a3a6f29ca2bb1a31/linter.py#L36-L60 for golint where some code from 2014 augments the GOPATH. Should we just remove this code?))

That is a custom workaround to find out GOPATH from the filesystem in case it's not set. Since you cannot develop in Go without GOPATH, I think the problem is that developers don't know how to make GOPATH visible to Sublime. For instance, on OSX, if you set GOPATH in .bashrc and then run Sublime from Spotlight, then GOPATH will not be seen by Sublime.

Considering that, before the end of 2018, GOPATH will be de-facto deprecated, I wouldn't invest in complex workarounds now. The only thing is: let's document how to configure GOPATH in case Sublime is not seeing the environment one. If a developer can can put it somewhere in SublimeLinter settings, just mention it both here and in SublimeLinter-golint, and that should be enough.

**Comment by kaste** [comment]
Okay I start by merging this one for the credits. ❤️

**Pull request merged**
